AllCops:
  DisabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideBrackets:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Lint/Debugger:
  Enabled: true

Lint/DefEndAlignment:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Security:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
